name: 'Example Check Run'
description: 'Checks to see if a badfile exists'


inputs:
  appId:
    description: "GitHub Application ID"
    required: true
  appPrivateKey:
    description: "GitHub Application Private Key as JWK"
    required: true

runs:
  using: "composite"
  steps:
    - uses: denoland/setup-deno@v1.1.1
      with:
        deno-version: v1.x # Run with latest stable Deno.
    - name: Run check run
      shell: bash
      run: deno run --allow-net --allow-read --allow-env .github/example-check-run/src/run.ts
      env:
        # Composite actions do not automatically propagate inputs to steps
        APP_ID: ${{ inputs.appId }}
        APP_PRIVATE_KEY: ${{ inputs.appPrivateKey }}

branding:
  icon: "box"
  color: "green"
